name: acafinder
channels:
  - conda-forge
  - glemaitre
  - defaults
dependencies:
  - aiohttp=3.7.4=py36h2bbff1b_1
  - argon2-cffi=20.1.0=py36h2bbff1b_1
  - async-timeout=3.0.1=py36haa95532_0
  - async_generator=1.10=py36h28b3542_0
  - attrs=20.3.0=pyhd3eb1b0_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - beautifulsoup4=4.9.3=pyha847dfd_0
  - blas=1.0=mkl
  - bleach=3.3.0=pyhd3eb1b0_0
  - boto=2.49.0=py36_0
  - boto3=1.17.23=pyhd3eb1b0_0
  - botocore=1.20.24=pyhd3eb1b0_1
  - brotlipy=0.7.0=py36h2bbff1b_1003
  - ca-certificates=2021.1.19=haa95532_1
  - cachetools=4.2.1=pyhd3eb1b0_0
  - certifi=2020.12.5=py36haa95532_0
  - cffi=1.14.5=py36hcd4344a_0
  - click=7.1.2=pyhd3eb1b0_0
  - colorama=0.4.4=pyhd3eb1b0_0
  - decorator=4.4.2=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - entrypoints=0.3=py36_0
  - freetype=2.10.4=hd328e21_0
  - gensim=3.8.3=py36hd77b12b_2
  - google-api-core=1.25.1=pyhd3eb1b0_0
  - google-auth=1.27.1=pyhd3eb1b0_0
  - google-cloud-core=1.6.0=pyhd3eb1b0_0
  - google-cloud-storage=1.36.1=pyhd3eb1b0_0
  - google-crc32c=1.1.2=py36h2bbff1b_0
  - google-resumable-media=1.2.0=pyhd3eb1b0_1
  - googleapis-common-protos=1.52.0=py36h2eaa2aa_0
  - icc_rt=2019.0.0=h0cc432a_1
  - icu=58.2=ha925a31_3
  - idna=2.10=pyhd3eb1b0_0
  - idna_ssl=1.1.0=py36haa95532_0
  - imbalanced-learn=0.2.1=py36_0
  - importlib-metadata=2.0.0=py_1
  - importlib_metadata=2.0.0=1
  - intel-openmp=2020.2=254
  - ipykernel=5.3.4=py36h5ca1d4c_0
  - ipython=7.16.1=py36h5ca1d4c_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - ipywidgets=7.6.3=pyhd3eb1b0_1
  - jedi=0.17.0=py36_0
  - jieba=0.39=pyh9f0ad1d_1
  - jinja2=2.11.3=pyhd3eb1b0_0
  - jmespath=0.10.0=py_0
  - joblib=1.0.1=pyhd3eb1b0_0
  - jpeg=9b=hb83a4c4_2
  - jsonschema=3.2.0=py_2
  - jupyter=1.0.0=py36_7
  - jupyter_client=6.1.7=py_0
  - jupyter_console=6.2.0=py_0
  - jupyter_core=4.7.1=py36haa95532_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_widgets=1.0.0=pyhd3eb1b0_1
  - kiwisolver=1.3.1=py36hd77b12b_0
  - libcrc32c=1.1.1=ha925a31_2
  - libpng=1.6.37=h2a8f88b_0
  - libprotobuf=3.14.0=h23ce68f_0
  - libsodium=1.0.18=h62dcd97_0
  - libtiff=4.1.0=h56a325e_1
  - lz4-c=1.9.3=h2bbff1b_0
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - markupsafe=1.1.1=py36he774522_0
  - matplotlib=3.3.4=py36haa95532_0
  - matplotlib-base=3.3.4=py36h49ac443_0
  - mistune=0.8.4=py36he774522_0
  - mkl=2020.2=256
  - mkl-service=2.3.0=py36h196d8e1_0
  - mkl_fft=1.3.0=py36h46781fe_0
  - mkl_random=1.1.1=py36h47e9c7a_0
  - msys2-conda-epoch=20160418=1
  - multidict=5.1.0=py36h2bbff1b_2
  - nbclient=0.5.3=pyhd3eb1b0_0
  - nbconvert=6.0.7=py36_0
  - nbformat=5.1.2=pyhd3eb1b0_1
  - nest-asyncio=1.5.1=pyhd3eb1b0_0
  - nltk=3.5=py_0
  - notebook=6.2.0=py36haa95532_0
  - numpy-base=1.19.2=py36ha3acd2a_0
  - olefile=0.46=py36_0
  - openssl=1.1.1j=h2bbff1b_0
  - packaging=20.9=pyhd3eb1b0_0
  - pandas=1.1.3=py36ha925a31_0
  - pandoc=2.11=h9490d1a_0
  - pandocfilters=1.4.3=py36haa95532_1
  - parso=0.8.1=pyhd3eb1b0_0
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=8.1.2=py36h4fa10fc_0
  - pip=21.0.1=py36haa95532_0
  - prometheus_client=0.9.0=pyhd3eb1b0_0
  - prompt_toolkit=3.0.8=0
  - protobuf=3.14.0=py36hd77b12b_1
  - pyasn1=0.4.8=py_0
  - pyasn1-modules=0.2.8=py_0
  - pycparser=2.20=py_2
  - pyopenssl=20.0.1=pyhd3eb1b0_1
  - pyparsing=2.4.7=pyhd3eb1b0_0
  - pyqt=5.9.2=py36h6538335_2
  - pyrsistent=0.17.3=py36he774522_0
  - pysocks=1.7.1=py36haa95532_0
  - python=3.6.12=h5500b2f_2
  - python-dateutil=2.8.1=pyhd3eb1b0_0
  - python_abi=3.6=1_cp36m
  - pytz=2021.1=pyhd3eb1b0_0
  - pywinpty=0.5.7=py36_0
  - pyzmq=20.0.0=py36hd77b12b_1
  - qt=5.9.7=vc14h73c81de_0
  - qtconsole=5.0.2=pyhd3eb1b0_0
  - qtpy=1.9.0=py_0
  - regex=2020.11.13=py36h2bbff1b_0
  - requests=2.25.1=pyhd3eb1b0_0
  - rsa=4.7.2=pyhd3eb1b0_1
  - s3transfer=0.3.4=pyhd3eb1b0_0
  - scikit-learn=0.24.1=py36hf11a4ad_0
  - scipy=1.5.2=py36h9439919_0
  - seaborn=0.11.1=pyhd3eb1b0_0
  - send2trash=1.5.0=pyhd3eb1b0_1
  - setuptools=52.0.0=py36haa95532_0
  - sip=4.19.8=py36h6538335_0
  - six=1.15.0=py36haa95532_0
  - smart_open=4.2.0=pyhd3eb1b0_0
  - soupsieve=2.2=pyhd3eb1b0_0
  - sqlite=3.33.0=h2a8f88b_0
  - terminado=0.9.2=py36haa95532_0
  - testpath=0.4.4=pyhd3eb1b0_0
  - threadpoolctl=2.1.0=pyh5ca1d4c_0
  - tk=8.6.10=he774522_0
  - tornado=6.1=py36h2bbff1b_0
  - tqdm=4.56.0=pyhd3eb1b0_0
  - traitlets=4.3.3=py36_0
  - typing-extensions=3.7.4.3=hd3eb1b0_0
  - typing_extensions=3.7.4.3=pyh06a4308_0
  - urllib3=1.26.3=pyhd3eb1b0_0
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - wcwidth=0.2.5=py_0
  - webencodings=0.5.1=py36_1
  - wheel=0.36.2=pyhd3eb1b0_0
  - widgetsnbextension=3.5.1=py36_0
  - win_inet_pton=1.1.0=py36haa95532_0
  - wincertstore=0.2=py36h7fe50ca_0
  - winpty=0.4.3=4
  - xz=5.2.5=h62dcd97_0
  - yarl=1.5.1=py36he774522_0
  - zeromq=4.3.3=ha925a31_3
  - zipp=3.4.0=pyhd3eb1b0_0
  - zlib=1.2.11=h62dcd97_4
  - zstd=1.4.5=h04227a9_0
  - pip:
    - asgiref==3.3.1
    - chardet==4.0.0
    - cryptography==3.4.6
    - cycler==0.10.0
    - django==3.1.7
    - djangorestframework==3.12.2
    - docker==4.4.4
    - english==2020.7.0
    - fasttext-win==0.8.3
    - future==0.18.2
    - monotonic==1.5
    - neo4j==4.2.1
    - neotime==1.7.4
    - numpy==1.19.5
    - pansi==2020.7.3
    - prompt-toolkit==2.0.10
    - py2neo==3.1.2
    - pygments==2.8.1
    - pypinyin==0.40.0
    - pywin32==227
    - sqlparse==0.4.1
    - websocket-client==0.58.0
    - wordcloud==1.8.1
    - wordninja==2.0.0
prefix: D:\anaconda3\envs\acafinder

